### ISSUE TITLE
.ec3 file extension not supported?

### ISSUE THREAD

**Issue by exnazirite** [jlw4049/MP4-Mux-Tool#26]
It seems like .ec3 audio streams should be supported (is listed in supported extensions when browsing for audio tracks) but drag-and-drop returns error and the audio file browser won't show them. 
Tried renaming the .ec3 file to .ac3 and the file was successfully muxed, log shows eac3 detected and mediainfo looks good, haven't checked playback yet.

**Comment by jlw4049** [comment]
I'll add this format in tomorrow, thanks for the report.
