### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by kkea08** [jlw4049/MP4-Mux-Tool#3]

**Comment by kkea08** [comment]
![image](https://user-images.githubusercontent.com/79582593/185774635-175515ef-f0d4-4c72-a4f0-dc23c7140f1f.png)

**Comment by jlw4049** [comment]
Everything okay?

**Comment by kkea08** [comment]
The first time I had this problem.

[image: image.png]


But later I chose Debug, now it's ok.
thank you🙂

[image: image.png]




ในวันที่ อา. 21 ส.ค. 2022 เวลา 19:52 jlw4049 ***@***.***>
เขียนว่า:

**Comment by jlw4049** [comment]
No problem. I have plans to enhance error handling in the near future.

**Comment by kkea08** [comment]
I hope to use it soon. 🙂✌

ในวันที่ อ. 23 ส.ค. 2022 เวลา 18:41 jlw4049 ***@***.***>
เขียนว่า:

**Comment by jlw4049** [comment]
Itll be what I work on next. Maybe start this week!

**Comment by kkea08** [comment]
That's great, I'll be waiting.😁

ในวันที่ อ. 23 ส.ค. 2022 เวลา 23:46 jlw4049 ***@***.***>
เขียนว่า:
